In [350]:
#先導入資料處理會用到的模組
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series, DataFrame
import pandas as pd
from glob import glob

# 可視化模組
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 機器學習模組
import sklearn

In [351]:
#讀檔
dataset_csv =pd.read_csv('train.csv')
dataset_csv.head()

                           mac_hash  sniffer_loc         created_time
0  0003ae8541d0e925fcee242287e2ad27           11  2018-12-07 16:48:08
1  00078611037990f7f36b722f22595fe7            3  2018-12-07 16:29:35
2  00078611037990f7f36b722f22595fe7            2  2018-12-07 16:30:41
3  00078611037990f7f36b722f22595fe7            4  2018-12-07 16:37:06
4  00078611037990f7f36b722f22595fe7            8  2018-12-07 16:37:07

In [352]:
labelset_csv=pd.read_csv('training-label.csv')
labelset_csv.head()

                           mac_hash  label
0  10f6ad2e3fa3b3da8ceb3fbd95658681      4
1  5272841b630d74290ec129c64dd6378b      0
2  8ab74d094708a27c9660e897b93a50f9      3
3  3d00887dd6e574dd63974bc6c69b23b0      1
4  6461fce7f6f184401c961fda75069262      1

In [353]:
label_0=[]
label_1=[]
label_2=[]
label_3=[]
label_4=[]
for item in range(len(labelset_csv['label'])):
    if labelset_csv['label'][item]==0: 
        label_0.append(1)
    else:
        label_0.append(0)
for item in range(len(labelset_csv['label'])):
    if labelset_csv['label'][item]==1:
        label_1.append(1)
    else:
        label_1.append(0)
for item in range(len(labelset_csv['label'])):
    if labelset_csv['label'][item]==2:
        label_2.append(1)
    else:
        label_2.append(0)
for item in range(len(labelset_csv['label'])):
    if labelset_csv['label'][item]==3:
        label_3.append(1)
    else:
        label_3.append(0)
for item in range(len(labelset_csv['label'])):
    if labelset_csv['label'][item]==4:
        label_4.append(1)
    else:
        label_4.append(0)

In [354]:
labeldata =pd.DataFrame({
                             "mac_hash":labelset_csv['mac_hash'],
                             "label_0":label_0,
                             "label_1":label_1,
                             "label_2":label_2,
                             "label_3":label_3,
                             "label_4":label_4,
                            
                        })
labeldata.to_csv('newlabel.csv',index=True)

In [355]:
labeldata_new=pd.read_csv('newlabel.csv')

In [356]:
labeldata.head()

,mac_hash,label_0,label_1,label_2,label_3,label_4
0,10f6ad2e3fa3b3da8ceb3fbd95658681,0,0,0,0,1
1,5272841b630d74290ec129c64dd6378b,1,0,0,0,0
2,8ab74d094708a27c9660e897b93a50f9,0,0,0,1,0
3,3d00887dd6e574dd63974bc6c69b23b0,0,1,0,0,0
4,6461fce7f6f184401c961fda75069262,0,1,0,0,0

In [357]:
#觀察幾列幾行
dataset_csv.shape

(41640, 3)

In [358]:
labelset_csv.shape

(6959, 2)

In [359]:
dataset_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41640 entries, 0 to 41639
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mac_hash      41640 non-null  object
 1   sniffer_loc   41640 non-null  int64
 2   created_time  41640 non-null  object
dtypes: int64(1), object(2)
memory usage: 976.1+ KB

In [360]:
#先將sniffer_loc改成str型態
dataset_csv['sniffer_loc']=dataset_csv['sniffer_loc'].astype(str)

In [361]:
#check
dataset_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41640 entries, 0 to 41639
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mac_hash      41640 non-null  object
 1   sniffer_loc   41640 non-null  object
 2   created_time  41640 non-null  object
dtypes: object(3)
memory usage: 976.1+ KB

In [362]:
#將相同mac_hash的資料的sniffer_loc整理在一起
dataset=dataset_csv.groupby(by='mac_hash').apply(lambda x:' '.join(x['sniffer_loc']))

In [363]:
dataset.head()

mac_hash
0003ae8541d0e925fcee242287e2ad27                                  11
00078611037990f7f36b722f22595fe7                   3 2 4 8 6 10 11 5
000ce31739b333d931813de403156844    6 8 13 10 11 3 2 7 5 9 1 4 12 14
0027240b2aeb1f7f3c053c073cafb452        10 12 13 14 9 7 8 4 2 5 6 11
0028a89964416dc9a8a66cc7fe25ef4e            10 4 3 2 6 9 12 13 11 14
dtype: object

In [364]:
#轉回int型態
dataset=dataset.str.split(" ",expand=True).fillna(0).astype(int)

In [365]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6959 entries, 0003ae8541d0e925fcee242287e2ad27 to fff2ca0333532d6348d5b4fa39028dd4
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6959 non-null   int64
 1   1       6959 non-null   int64
 2   2       6959 non-null   int64
 3   3       6959 non-null   int64
 4   4       6959 non-null   int64
 5   5       6959 non-null   int64
 6   6       6959 non-null   int64
 7   7       6959 non-null   int64
 8   8       6959 non-null   int64
 9   9       6959 non-null   int64
 10  10      6959 non-null   int64
 11  11      6959 non-null   int64
 12  12      6959 non-null   int64
 13  13      6959 non-null   int64
dtypes: int64(14)
memory usage: 815.5+ KB

In [366]:
#check
dataset.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
mac_hash,,,,,,,,,,,,,,
0003ae8541d0e925fcee242287e2ad27,11,0,0,0,0,0,0,0,0,0,0,0,0,0
00078611037990f7f36b722f22595fe7,3,2,4,8,6,10,11,5,0,0,0,0,0,0
000ce31739b333d931813de403156844,6,8,13,10,11,3,2,7,5,9,1,4,12,14
0027240b2aeb1f7f3c053c073cafb452,10,12,13,14,9,7,8,4,2,5,6,11,0,0
0028a89964416dc9a8a66cc7fe25ef4e,10,4,3,2,6,9,12,13,11,14,0,0,0,0

In [367]:
#將相同mac_hash的資料的created_time整理在一起
dataset2=dataset_csv.groupby(by='mac_hash').apply(lambda x:[','.join(x['created_time'])])

In [368]:
#check
dataset2.head()

mac_hash
0003ae8541d0e925fcee242287e2ad27                                [2018-12-07 16:48:08]
00078611037990f7f36b722f22595fe7    [2018-12-07 16:29:35,2018-12-07 16:30:41,2018-...
000ce31739b333d931813de403156844    [2018-12-06 14:44:29,2018-12-06 14:44:29,2018-...
0027240b2aeb1f7f3c053c073cafb452    [2018-12-08 13:46:25,2018-12-08 13:48:39,2018-...
0028a89964416dc9a8a66cc7fe25ef4e    [2018-12-08 10:54:12,2018-12-08 11:02:20,2018-...
dtype: object

In [369]:
#transfer to csv
dataset_new=pd.DataFrame({
                             "sniffer_loc_0":dataset[0],
                             "sniffer_loc_1":dataset[1],
                             "sniffer_loc_2":dataset[2],
                             "sniffer_loc_3":dataset[3],
                             "sniffer_loc_4":dataset[4],
                             "sniffer_loc_5":dataset[5],
                             "sniffer_loc_6":dataset[6],
                             "sniffer_loc_7":dataset[7],
                             "sniffer_loc_8":dataset[8],
                             "sniffer_loc_9":dataset[9],
                             "sniffer_loc_10":dataset[10],
                             "sniffer_loc_11":dataset[11],
                             "sniffer_loc_12":dataset[12],
                             "sniffer_loc_13":dataset[13],
                        })
dataset_new.to_csv('sniffer.csv',index=True)

dataset_new=pd.DataFrame({
                             "created_time":dataset2
                        })
dataset_new.to_csv('createtime.csv',index=True)

In [370]:
#read file
sniffer_csv = pd.read_csv('sniffer.csv')
create_time_csv=pd.read_csv('createtime.csv')

In [371]:
#check
sniffer_csv.head(10)
#create_time_csv.head(10)

,mac_hash,sniffer_loc_0,sniffer_loc_1,sniffer_loc_2,sniffer_loc_3,sniffer_loc_4,sniffer_loc_5,sniffer_loc_6,sniffer_loc_7,sniffer_loc_8,sniffer_loc_9,sniffer_loc_10,sniffer_loc_11,sniffer_loc_12,sniffer_loc_13
0,0003ae8541d0e925fcee242287e2ad27,11,0,0,0,0,0,0,0,0,0,0,0,0,0
1,00078611037990f7f36b722f22595fe7,3,2,4,8,6,10,11,5,0,0,0,0,0,0
2,000ce31739b333d931813de403156844,6,8,13,10,11,3,2,7,5,9,1,4,12,14
3,0027240b2aeb1f7f3c053c073cafb452,10,12,13,14,9,7,8,4,2,5,6,11,0,0
4,0028a89964416dc9a8a66cc7fe25ef4e,10,4,3,2,6,9,12,13,11,14,0,0,0,0
5,002ccce0dc6384e91e6aaa988b542c45,3,0,0,0,0,0,0,0,0,0,0,0,0,0
6,00414318025c30f1360225ad736aa298,3,2,5,6,4,7,11,13,12,10,9,0,0,0
7,0041999224addbf0753762647ac2166b,6,4,2,5,3,9,12,11,10,13,8,0,0,0
8,0044e62541626e25e041b4baf3daea4c,3,2,5,4,8,6,9,10,12,14,13,0,0,0
9,004c76bfe9f7b20f3651e0bcbd8eee9e,5,4,2,3,1,6,9,8,0,0,0,0,0,0

# merge file

In [372]:
#merge sniffer 和 createtime 
final=sniffer_csv.merge(create_time_csv, on='mac_hash')

In [373]:
#transfer to csv
final.to_csv('final_train.csv',index=True)

In [374]:
#read file
dataset_train=pd.read_csv('final_train.csv')
#check
print(dataset_train.shape)
dataset_train.head(10)

(6959, 17)

,Unnamed: 0,mac_hash,sniffer_loc_0,sniffer_loc_1,sniffer_loc_2,sniffer_loc_3,sniffer_loc_4,sniffer_loc_5,sniffer_loc_6,sniffer_loc_7,sniffer_loc_8,sniffer_loc_9,sniffer_loc_10,sniffer_loc_11,sniffer_loc_12,sniffer_loc_13,created_time
0,0,0003ae8541d0e925fcee242287e2ad27,11,0,0,0,0,0,0,0,0,0,0,0,0,0,['2018-12-07 16:48:08']
1,1,00078611037990f7f36b722f22595fe7,3,2,4,8,6,10,11,5,0,0,0,0,0,0,"['2018-12-07 16:29:35,2018-12-07 16:30:41,2018..."
2,2,000ce31739b333d931813de403156844,6,8,13,10,11,3,2,7,5,9,1,4,12,14,"['2018-12-06 14:44:29,2018-12-06 14:44:29,2018..."
3,3,0027240b2aeb1f7f3c053c073cafb452,10,12,13,14,9,7,8,4,2,5,6,11,0,0,"['2018-12-08 13:46:25,2018-12-08 13:48:39,2018..."
4,4,0028a89964416dc9a8a66cc7fe25ef4e,10,4,3,2,6,9,12,13,11,14,0,0,0,0,"['2018-12-08 10:54:12,2018-12-08 11:02:20,2018..."
5,5,002ccce0dc6384e91e6aaa988b542c45,3,0,0,0,0,0,0,0,0,0,0,0,0,0,['2018-12-08 15:34:01']
6,6,00414318025c30f1360225ad736aa298,3,2,5,6,4,7,11,13,12,10,9,0,0,0,"['2018-12-06 18:42:27,2018-12-06 18:42:27,2018..."
7,7,0041999224addbf0753762647ac2166b,6,4,2,5,3,9,12,11,10,13,8,0,0,0,"['2018-12-06 13:52:06,2018-12-06 14:10:37,2018..."
8,8,0044e62541626e25e041b4baf3daea4c,3,2,5,4,8,6,9,10,12,14,13,0,0,0,"['2018-12-08 15:01:04,2018-12-08 15:01:04,2018..."
9,9,004c76bfe9f7b20f3651e0bcbd8eee9e,5,4,2,3,1,6,9,8,0,0,0,0,0,0,"['2018-12-06 13:15:35,2018-12-06 13:15:34,2018..."

In [375]:
dataset_train=dataset_train.drop(['Unnamed: 0'],axis=1)

In [376]:
#check
dataset_train.head()

,mac_hash,sniffer_loc_0,sniffer_loc_1,sniffer_loc_2,sniffer_loc_3,sniffer_loc_4,sniffer_loc_5,sniffer_loc_6,sniffer_loc_7,sniffer_loc_8,sniffer_loc_9,sniffer_loc_10,sniffer_loc_11,sniffer_loc_12,sniffer_loc_13,created_time
0,0003ae8541d0e925fcee242287e2ad27,11,0,0,0,0,0,0,0,0,0,0,0,0,0,['2018-12-07 16:48:08']
1,00078611037990f7f36b722f22595fe7,3,2,4,8,6,10,11,5,0,0,0,0,0,0,"['2018-12-07 16:29:35,2018-12-07 16:30:41,2018..."
2,000ce31739b333d931813de403156844,6,8,13,10,11,3,2,7,5,9,1,4,12,14,"['2018-12-06 14:44:29,2018-12-06 14:44:29,2018..."
3,0027240b2aeb1f7f3c053c073cafb452,10,12,13,14,9,7,8,4,2,5,6,11,0,0,"['2018-12-08 13:46:25,2018-12-08 13:48:39,2018..."
4,0028a89964416dc9a8a66cc7fe25ef4e,10,4,3,2,6,9,12,13,11,14,0,0,0,0,"['2018-12-08 10:54:12,2018-12-08 11:02:20,2018..."

In [377]:
dataset_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6959 entries, 0 to 6958
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mac_hash        6959 non-null   object
 1   sniffer_loc_0   6959 non-null   int64
 2   sniffer_loc_1   6959 non-null   int64
 3   sniffer_loc_2   6959 non-null   int64
 4   sniffer_loc_3   6959 non-null   int64
 5   sniffer_loc_4   6959 non-null   int64
 6   sniffer_loc_5   6959 non-null   int64
 7   sniffer_loc_6   6959 non-null   int64
 8   sniffer_loc_7   6959 non-null   int64
 9   sniffer_loc_8   6959 non-null   int64
 10  sniffer_loc_9   6959 non-null   int64
 11  sniffer_loc_10  6959 non-null   int64
 12  sniffer_loc_11  6959 non-null   int64
 13  sniffer_loc_12  6959 non-null   int64
 14  sniffer_loc_13  6959 non-null   int64
 15  created_time    6959 non-null   object
dtypes: int64(14), object(2)
memory usage: 870.0+ KB

In [378]:
final_twice=dataset_train.merge(labeldata_new, on='mac_hash')

In [379]:
final_twice.to_csv('dataset_train.csv',index=True)

In [380]:
final_data=pd.read_csv('dataset_train.csv')

In [381]:
#check
final_data.head(10)

,Unnamed: 0,mac_hash,sniffer_loc_0,sniffer_loc_1,sniffer_loc_2,sniffer_loc_3,sniffer_loc_4,sniffer_loc_5,sniffer_loc_6,sniffer_loc_7,...,sniffer_loc_11,sniffer_loc_12,sniffer_loc_13,created_time,Unnamed: 0.1,label_0,label_1,label_2,label_3,label_4
0,0,0003ae8541d0e925fcee242287e2ad27,11,0,0,0,0,0,0,0,...,0,0,0,['2018-12-07 16:48:08'],4184,1,0,0,0,0
1,1,00078611037990f7f36b722f22595fe7,3,2,4,8,6,10,11,5,...,0,0,0,"['2018-12-07 16:29:35,2018-12-07 16:30:41,2018...",3007,0,1,0,0,0
2,2,000ce31739b333d931813de403156844,6,8,13,10,11,3,2,7,...,4,12,14,"['2018-12-06 14:44:29,2018-12-06 14:44:29,2018...",2913,0,0,0,1,0
3,3,0027240b2aeb1f7f3c053c073cafb452,10,12,13,14,9,7,8,4,...,11,0,0,"['2018-12-08 13:46:25,2018-12-08 13:48:39,2018...",3425,0,0,0,0,1
4,4,0028a89964416dc9a8a66cc7fe25ef4e,10,4,3,2,6,9,12,13,...,0,0,0,"['2018-12-08 10:54:12,2018-12-08 11:02:20,2018...",1675,0,0,0,0,1
5,5,002ccce0dc6384e91e6aaa988b542c45,3,0,0,0,0,0,0,0,...,0,0,0,['2018-12-08 15:34:01'],2532,1,0,0,0,0
6,6,00414318025c30f1360225ad736aa298,3,2,5,6,4,7,11,13,...,0,0,0,"['2018-12-06 18:42:27,2018-12-06 18:42:27,2018...",2811,0,0,0,0,1
7,7,0041999224addbf0753762647ac2166b,6,4,2,5,3,9,12,11,...,0,0,0,"['2018-12-06 13:52:06,2018-12-06 14:10:37,2018...",4842,0,0,0,0,1
8,8,0044e62541626e25e041b4baf3daea4c,3,2,5,4,8,6,9,10,...,0,0,0,"['2018-12-08 15:01:04,2018-12-08 15:01:04,2018...",3239,0,0,0,0,1
9,9,004c76bfe9f7b20f3651e0bcbd8eee9e,5,4,2,3,1,6,9,8,...,0,0,0,"['2018-12-06 13:15:35,2018-12-06 13:15:34,2018...",6598,0,1,0,0,0

In [382]:
features_drop=['mac_hash','created_time','Unnamed: 0','Unnamed: 0.1']
final_data=final_data.drop(features_drop,axis=1)

In [383]:
final_data.head()

,sniffer_loc_0,sniffer_loc_1,sniffer_loc_2,sniffer_loc_3,sniffer_loc_4,sniffer_loc_5,sniffer_loc_6,sniffer_loc_7,sniffer_loc_8,sniffer_loc_9,sniffer_loc_10,sniffer_loc_11,sniffer_loc_12,sniffer_loc_13,label_0,label_1,label_2,label_3,label_4
0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,3,2,4,8,6,10,11,5,0,0,0,0,0,0,0,1,0,0,0
2,6,8,13,10,11,3,2,7,5,9,1,4,12,14,0,0,0,1,0
3,10,12,13,14,9,7,8,4,2,5,6,11,0,0,0,0,0,0,1
4,10,4,3,2,6,9,12,13,11,14,0,0,0,0,0,0,0,0,1

In [384]:
#設定預測目標變數與解釋變數
final_drop=['label_0','label_1','label_2','label_3','label_4']
final_dataset =final_data.drop(final_drop,axis=1)
final_target=final_data[final_drop]
final_dataset.shape, final_target.shape

((6959, 14), (6959, 5))

In [385]:
#目前的所有解釋變數
final_dataset.head()

,sniffer_loc_0,sniffer_loc_1,sniffer_loc_2,sniffer_loc_3,sniffer_loc_4,sniffer_loc_5,sniffer_loc_6,sniffer_loc_7,sniffer_loc_8,sniffer_loc_9,sniffer_loc_10,sniffer_loc_11,sniffer_loc_12,sniffer_loc_13
0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
1,3,2,4,8,6,10,11,5,0,0,0,0,0,0
2,6,8,13,10,11,3,2,7,5,9,1,4,12,14
3,10,12,13,14,9,7,8,4,2,5,6,11,0,0
4,10,4,3,2,6,9,12,13,11,14,0,0,0,0

In [386]:
#確認欄位的資料型態均為數值型別
final_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6959 entries, 0 to 6958
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sniffer_loc_0   6959 non-null   int64
 1   sniffer_loc_1   6959 non-null   int64
 2   sniffer_loc_2   6959 non-null   int64
 3   sniffer_loc_3   6959 non-null   int64
 4   sniffer_loc_4   6959 non-null   int64
 5   sniffer_loc_5   6959 non-null   int64
 6   sniffer_loc_6   6959 non-null   int64
 7   sniffer_loc_7   6959 non-null   int64
 8   sniffer_loc_8   6959 non-null   int64
 9   sniffer_loc_9   6959 non-null   int64
 10  sniffer_loc_10  6959 non-null   int64
 11  sniffer_loc_11  6959 non-null   int64
 12  sniffer_loc_12  6959 non-null   int64
 13  sniffer_loc_13  6959 non-null   int64
dtypes: int64(14)
memory usage: 761.3 KB

# 建置模型

In [387]:
#設定seaborn為預設繪圖library
sns.set()

In [388]:
from keras.models import Sequential
from keras.layers.core import Dense,Activation
from keras.optimizers import Adam
from sklearn import preprocessing

In [389]:
#建立模型函式
def build_model():
    model =Sequential()
    model.add(Dense(input_dim=14,units=40))
    model.add(Activation('relu'))
    model.add(Dense(units=100))
    model.add(Activation('relu'))
    model.add(Dense(units=10))
    model.add(Activation('relu'))
    model.add(Dense(units=5))
    model.add(Activation('sigmoid'))
    model.summary()
    return model

In [390]:
def show_train_history(train_history,train,validation,label):
    plt.plot(train_history.history[train])
    plt.plot(train_history.history[validation])
    plt.title('Train History')
    plt.ylabel(label)
    plt.xlabel('Epoch')
    plt.legend(['train','validation'],loc='upper left')
    plt.show()

In [391]:
#feature標準化
minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))
scaledFeatures=minmax_scale.fit_transform(final_dataset)

In [392]:
#訓練模型
model = build_model()

#開始訓練模型
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['acc'])
train_hitory=model.fit(scaledFeatures,final_target,validation_split=0.2,batch_size=30,epochs=100)

#顯示訓練結果
score=model.evaluate(x=scaledFeatures,y=final_target)
print('\nTrain Loss:',score[0])
print ('\nTrain Acc:', score[1])

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_44 (Dense)             (None, 40)                600
_________________________________________________________________
activation_44 (Activation)   (None, 40)                0
_________________________________________________________________
dense_45 (Dense)             (None, 100)               4100
_________________________________________________________________
activation_45 (Activation)   (None, 100)               0
_________________________________________________________________
dense_46 (Dense)             (None, 10)                1010
_________________________________________________________________
activation_46 (Activation)   (None, 10)                0
_________________________________________________________________
dense_47 (Dense)             (None, 5)                 55
_________________________________________________________________
activation_47 (Activation)   (None, 5)                 0
=================================================================
Total params: 5,765
Trainable params: 5,765
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
186/186 [==============================] - 2s 3ms/step - loss: 0.5241 - acc: 0.4727 - val_loss: 0.2444 - val_acc: 0.6904
Epoch 2/100
186/186 [==============================] - 0s 2ms/step - loss: 0.2245 - acc: 0.7409 - val_loss: 0.1962 - val_acc: 0.7680
Epoch 3/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1844 - acc: 0.8050 - val_loss: 0.1718 - val_acc: 0.8103
Epoch 4/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1606 - acc: 0.8384 - val_loss: 0.1581 - val_acc: 0.8312
Epoch 5/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1463 - acc: 0.8481 - val_loss: 0.1579 - val_acc: 0.8261
Epoch 6/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1429 - acc: 0.8516 - val_loss: 0.1424 - val_acc: 0.8491
Epoch 7/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1353 - acc: 0.8541 - val_loss: 0.1391 - val_acc: 0.8484
Epoch 8/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1327 - acc: 0.8543 - val_loss: 0.1351 - val_acc: 0.8441
Epoch 9/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1257 - acc: 0.8606 - val_loss: 0.1327 - val_acc: 0.8477
Epoch 10/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1284 - acc: 0.8592 - val_loss: 0.1323 - val_acc: 0.8420
Epoch 11/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1256 - acc: 0.8593 - val_loss: 0.1287 - val_acc: 0.8578
Epoch 12/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1233 - acc: 0.8538 - val_loss: 0.1258 - val_acc: 0.8491
Epoch 13/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1197 - acc: 0.8627 - val_loss: 0.1246 - val_acc: 0.8520
Epoch 14/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1212 - acc: 0.8620 - val_loss: 0.1266 - val_acc: 0.8570
Epoch 15/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1139 - acc: 0.8752 - val_loss: 0.1250 - val_acc: 0.8585
Epoch 16/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1165 - acc: 0.8728 - val_loss: 0.1192 - val_acc: 0.8614
Epoch 17/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1092 - acc: 0.8782 - val_loss: 0.1225 - val_acc: 0.8671
Epoch 18/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1141 - acc: 0.8770 - val_loss: 0.1177 - val_acc: 0.8678
Epoch 19/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1075 - acc: 0.8790 - val_loss: 0.1159 - val_acc: 0.8728
Epoch 20/100
186/186 [==============================] - 0s 1ms/step - loss: 0.1063 - acc: 0.8836 - val_loss: 0.1157 - val_acc: 0.8779
Epoch 21/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1036 - acc: 0.8862 - val_loss: 0.1171 - val_acc: 0.8772
Epoch 22/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1045 - acc: 0.8889 - val_loss: 0.1119 - val_acc: 0.8851
Epoch 23/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0985 - acc: 0.8982 - val_loss: 0.1131 - val_acc: 0.8786
Epoch 24/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1035 - acc: 0.8889 - val_loss: 0.1105 - val_acc: 0.8915
Epoch 25/100
186/186 [==============================] - 0s 2ms/step - loss: 0.1002 - acc: 0.8978 - val_loss: 0.1119 - val_acc: 0.8879
Epoch 26/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0970 - acc: 0.9019 - val_loss: 0.1148 - val_acc: 0.8743
Epoch 27/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0988 - acc: 0.8930 - val_loss: 0.1073 - val_acc: 0.8958
Epoch 28/100
186/186 [==============================] - 0s 2ms/step - loss: 0.0954 - acc: 0.9012 - val_loss: 0.1053 - val_acc: 0.9001
Epoch 29/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0972 - acc: 0.9021 - val_loss: 0.1087 - val_acc: 0.8872
Epoch 30/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0971 - acc: 0.8979 - val_loss: 0.1033 - val_acc: 0.8951
Epoch 31/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0896 - acc: 0.9093 - val_loss: 0.1005 - val_acc: 0.9052
Epoch 32/100
186/186 [==============================] - 0s 2ms/step - loss: 0.0867 - acc: 0.9116 - val_loss: 0.1130 - val_acc: 0.8786
Epoch 33/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0936 - acc: 0.8967 - val_loss: 0.1029 - val_acc: 0.9059
Epoch 34/100
186/186 [==============================] - 0s 2ms/step - loss: 0.0930 - acc: 0.9039 - val_loss: 0.1011 - val_acc: 0.9059
Epoch 35/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0849 - acc: 0.9181 - val_loss: 0.1011 - val_acc: 0.8944
Epoch 36/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0895 - acc: 0.9084 - val_loss: 0.0999 - val_acc: 0.9088
Epoch 37/100
186/186 [==============================] - 0s 2ms/step - loss: 0.0870 - acc: 0.9034 - val_loss: 0.0987 - val_acc: 0.9045
Epoch 38/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0846 - acc: 0.9145 - val_loss: 0.0993 - val_acc: 0.9045
Epoch 39/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0821 - acc: 0.9132 - val_loss: 0.1006 - val_acc: 0.9037
Epoch 40/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0805 - acc: 0.9161 - val_loss: 0.0993 - val_acc: 0.9080
Epoch 41/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0859 - acc: 0.9132 - val_loss: 0.0955 - val_acc: 0.9088
Epoch 42/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0829 - acc: 0.9149 - val_loss: 0.0988 - val_acc: 0.9095
Epoch 43/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0811 - acc: 0.9166 - val_loss: 0.0924 - val_acc: 0.9159
Epoch 44/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0851 - acc: 0.9066 - val_loss: 0.0943 - val_acc: 0.9131
Epoch 45/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0804 - acc: 0.9143 - val_loss: 0.0999 - val_acc: 0.9059
Epoch 46/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0818 - acc: 0.9166 - val_loss: 0.0967 - val_acc: 0.9095
Epoch 47/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0814 - acc: 0.9128 - val_loss: 0.0913 - val_acc: 0.9080
Epoch 48/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0771 - acc: 0.9212 - val_loss: 0.0934 - val_acc: 0.9124
Epoch 49/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0796 - acc: 0.9200 - val_loss: 0.0949 - val_acc: 0.9088
Epoch 50/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0746 - acc: 0.9242 - val_loss: 0.0953 - val_acc: 0.9037
Epoch 51/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0745 - acc: 0.9216 - val_loss: 0.0925 - val_acc: 0.9124
Epoch 52/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0732 - acc: 0.9226 - val_loss: 0.0961 - val_acc: 0.9088
Epoch 53/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0761 - acc: 0.9174 - val_loss: 0.0931 - val_acc: 0.9145
Epoch 54/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0774 - acc: 0.9235 - val_loss: 0.0942 - val_acc: 0.9116
Epoch 55/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0761 - acc: 0.9217 - val_loss: 0.0963 - val_acc: 0.9124
Epoch 56/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0792 - acc: 0.9214 - val_loss: 0.0914 - val_acc: 0.9138
Epoch 57/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0688 - acc: 0.9302 - val_loss: 0.0928 - val_acc: 0.9145
Epoch 58/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0734 - acc: 0.9263 - val_loss: 0.0942 - val_acc: 0.9095
Epoch 59/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0701 - acc: 0.9309 - val_loss: 0.0912 - val_acc: 0.9080
Epoch 60/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0752 - acc: 0.9232 - val_loss: 0.0903 - val_acc: 0.9174
Epoch 61/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0695 - acc: 0.9292 - val_loss: 0.0957 - val_acc: 0.9045
Epoch 62/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0717 - acc: 0.9296 - val_loss: 0.0925 - val_acc: 0.9102
Epoch 63/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0748 - acc: 0.9237 - val_loss: 0.0933 - val_acc: 0.9102
Epoch 64/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0687 - acc: 0.9324 - val_loss: 0.0906 - val_acc: 0.9059
Epoch 65/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0695 - acc: 0.9318 - val_loss: 0.0907 - val_acc: 0.9124
Epoch 66/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0708 - acc: 0.9287 - val_loss: 0.0893 - val_acc: 0.9152
Epoch 67/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0661 - acc: 0.9356 - val_loss: 0.0906 - val_acc: 0.9116
Epoch 68/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0700 - acc: 0.9270 - val_loss: 0.0888 - val_acc: 0.9174
Epoch 69/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0726 - acc: 0.9277 - val_loss: 0.0927 - val_acc: 0.9052
Epoch 70/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0675 - acc: 0.9345 - val_loss: 0.0903 - val_acc: 0.9116
Epoch 71/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0691 - acc: 0.9319 - val_loss: 0.0916 - val_acc: 0.9073
Epoch 72/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0646 - acc: 0.9358 - val_loss: 0.0895 - val_acc: 0.9195
Epoch 73/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0675 - acc: 0.9314 - val_loss: 0.0915 - val_acc: 0.9116
Epoch 74/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0671 - acc: 0.9311 - val_loss: 0.0902 - val_acc: 0.9109
Epoch 75/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0698 - acc: 0.9295 - val_loss: 0.0926 - val_acc: 0.9188
Epoch 76/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0672 - acc: 0.9344 - val_loss: 0.0933 - val_acc: 0.9095
Epoch 77/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0730 - acc: 0.9267 - val_loss: 0.0907 - val_acc: 0.9124
Epoch 78/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0637 - acc: 0.9347 - val_loss: 0.0900 - val_acc: 0.9138
Epoch 79/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0666 - acc: 0.9363 - val_loss: 0.0895 - val_acc: 0.9217
Epoch 80/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0678 - acc: 0.9363 - val_loss: 0.0916 - val_acc: 0.9159
Epoch 81/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0635 - acc: 0.9360 - val_loss: 0.0879 - val_acc: 0.9203
Epoch 82/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0622 - acc: 0.9433 - val_loss: 0.0890 - val_acc: 0.9210
Epoch 83/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0634 - acc: 0.9374 - val_loss: 0.0912 - val_acc: 0.9231
Epoch 84/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0673 - acc: 0.9346 - val_loss: 0.0904 - val_acc: 0.9095
Epoch 85/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0638 - acc: 0.9335 - val_loss: 0.0888 - val_acc: 0.9145
Epoch 86/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0665 - acc: 0.9316 - val_loss: 0.0926 - val_acc: 0.9030
Epoch 87/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0631 - acc: 0.9379 - val_loss: 0.0914 - val_acc: 0.9124
Epoch 88/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0623 - acc: 0.9376 - val_loss: 0.0867 - val_acc: 0.9203
Epoch 89/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0614 - acc: 0.9394 - val_loss: 0.0853 - val_acc: 0.9174
Epoch 90/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0627 - acc: 0.9362 - val_loss: 0.0898 - val_acc: 0.9138
Epoch 91/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0626 - acc: 0.9359 - val_loss: 0.0858 - val_acc: 0.9246
Epoch 92/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0596 - acc: 0.9439 - val_loss: 0.0909 - val_acc: 0.9138
Epoch 93/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0651 - acc: 0.9364 - val_loss: 0.0879 - val_acc: 0.9181
Epoch 94/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0616 - acc: 0.9363 - val_loss: 0.0876 - val_acc: 0.9224
Epoch 95/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0610 - acc: 0.9399 - val_loss: 0.0909 - val_acc: 0.9116
Epoch 96/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0605 - acc: 0.9413 - val_loss: 0.0882 - val_acc: 0.9195
Epoch 97/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0604 - acc: 0.9415 - val_loss: 0.0880 - val_acc: 0.9188
Epoch 98/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0612 - acc: 0.9381 - val_loss: 0.0893 - val_acc: 0.9145
Epoch 99/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0616 - acc: 0.9406 - val_loss: 0.0907 - val_acc: 0.9102
Epoch 100/100
186/186 [==============================] - 0s 1ms/step - loss: 0.0589 - acc: 0.9406 - val_loss: 0.0891 - val_acc: 0.9152
218/218 [==============================] - 0s 660us/step - loss: 0.0645 - acc: 0.9358

Train Loss: 0.06445635855197906

Train Acc: 0.9357666373252869

In [394]:
#儲存模型
model.save('dnnformarathon.h5')